name: Build (Nintendo 3DS)

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  n3ds:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          sudo apt install -y git build-essential pkg-config libusb-1.0-0-dev libsdl2-dev ninja-build build-essential pkg-config python3 zlib1g-dev libaudiofile-dev
      - name: Build
        run: make -j4